version: "3.8"
services:
    app:
        build: .
        ports:
            - "3000:8080"
        environment:
            HOST: 0.0.0.0
            PORT: 8080
            NUXT_PUBLIC_WEBSOCKET_HOST: "ws://localhost:1234/"
            NUXT_PUBLIC_EDITOR_WEBSOCKET_HOST: "ws://localhost:1234/"
    websocket:
        image: node:18-alpine
        command: npx y-websocket
        ports:
            - "1234:1234"
        environment:
            HOST: 0.0.0.0
            PORT: 1234